name: Test

on:
  push:

jobs:
  test-tarantool:
    strategy:
      fail-fast: false
      matrix:
        tarantool: ['1.10', '2.5', '2.6', '2.7', '2.8']

    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Run regression testing
        run: make test

      - name: Run performance testing
        run: make perf

  test-luajit:
    strategy:
      fail-fast: false

    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Setup LuaJIT
        run: sudo apt install -y luajit

      - name: Load checks module in LuaJIT
        run: luajit -l checks -e 'os.exit()'
