name: Test

on:
  push:

jobs:
  test-tarantool:
    strategy:
      fail-fast: false
      matrix:
        tarantool: ['1.10','2.11', '3.3']

    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - uses: tarantool/setup-tarantool@v3
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Setup tt
        run: |
          curl -L https://tarantool.io/release/2/installer.sh | sudo bash
          sudo apt install -y tt
          tt version

      - name: Run static analysis
        run: make lint

      - name: Run regression testing
        run: make test

      - name: Run performance testing
        run: make perf

  test-luajit:
    strategy:
      fail-fast: false

    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - name: Setup LuaJIT
        run: sudo apt install -y luajit

      - name: Load checks module in LuaJIT
        run: luajit -l checks -e 'os.exit()'
